parameters:
#    results.example.class: bet\resultBundle\Example

services:
#    results.example:
#        class: %results.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
